version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./html:/usr/share/nginx/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./etc/nginx/localhost.key:/etc/nginx/localhost.key
  service:
    build:
      context: .
    entrypoint:
      /service
